# fly.toml app configuration file generated for postowldev on 2023-06-12T17:45:42+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "postowldev"
primary_region = "lhr"

[experimental]
  cmd = ["start.sh"]
  entrypoint = ["sh"]

[env]
  DB_PATH = "/data/powstowldev_data/db.sqlite3"
  PORT = "3000"

[[mounts]]
  source = "postowldev_data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
